### ISSUE TITLE
bash, dash ash or whatever shell on docker container

### ISSUE THREAD

**Issue by Rugaliz** [juanfont/headscale#1007]
So I'm running the docker version and sometimes I need to run some commands that require a response. 
I can't seam to run any of the popular shells on the docker version (I'm using the latest docker container BTW), dunno if I missed something but the installation docks don't give much insight on what is available.

Is it possible to modify the latest container image to feature a common shell?

Cheers

**Comment by kradalby** [comment]
Hi

I wanted to keep this, but we had some people insisting this was bad practice and we should not have it in the container. I disagree and only use the `Dockerfile` marked with Debug since it contains a shell.

I suspect I will ditch the current Dockerfile at some point in the future in favour of our build system, I'll keep this in mind to fix it.

In the meantime, I would use the Debug image if you need shell. Sorry for the inconvenience. 

For reference, this is the discussion changing the container images: https://github.com/juanfont/headscale/pull/214
at the time, we gave in to the arguments, but they have been deemed highly impractical and when we have some time, we will revert this. Life is to short to deal with this.
