### ISSUE TITLE
OIDC configure expiry time

### ISSUE THREAD

**Issue by Charlez700** [juanfont/headscale#1176]
Hi,
I run Headscale 0.17 and planning to upgrade to 0.18. on my test server running 0.18 I see that the oidc users have a default expiration time of 60 minutes.

how do I configure the expiration time for oidc users to make it longer?

thanks.

**Comment by evenh** [comment]
The implementation uses whatever your OIDC provider puts in the exp-field of the issued token.

It may indicate that your provider has a default token lifetime of 1hr.

**Comment by ported-pw** [comment]
I just came across this while wondering why my node was getting such a short expiry time or expiring at all for that matter. I take it that OIDC token refresh is not implemented yet? Are there any plans for doing that? For example Keycloak uses very short lived tokens and prefers to let users refresh often to ensure that they have up to date tokens/credentials. This way I'd have to make it somewhat less secure and configure the access token lifetime to something usable like an entire week or month which doesn't sound great.

**Comment by Charlez700** [comment]
Hhhmmmm that may be a problem then because all my OIDC clients will disconnect once an hour. 

>  I take it that OIDC token refresh is not implemented yet?

I think the same yes.

**Comment by ported-pw** [comment]
Or maybe alternatively it could for now be made possible to disable this https://github.com/juanfont/headscale/pull/1067?

**Comment by reynico** [comment]
> Maybe it could be made possible to disable expiring nodes on token expiry for now until the OIDC implementation is complete? See #1067

maybe passing a default expiry time by configuration?

**Comment by evenh** [comment]
> I just came across this while wondering why my node was getting such a short expiry time or expiring at all for that matter. I take it that OIDC token refresh is not implemented yet? Are there any plans for doing that? For example Keycloak uses very short lived tokens (5 minutes by default) and prefers to let users refresh often to ensure that they have up to date tokens/credentials. This way I'd have to make it somewhat less secure and configure the access token lifetime to something usable like an entire week or month which doesn't sound great.

Only the ID token from OIDC is used per right now. Related code and discussions:
 - https://github.com/juanfont/headscale/pull/126
 - https://github.com/juanfont/headscale/issues/935
 - https://github.com/juanfont/headscale/pull/1067

Looking forward, there is a couple of obvious things that could be done:
- Add a configuration option/environment variable that overrides whatever expiry comes from OIDC (or possibly when running without OIDC). `HS_OVERRIDE_DEFAULT_EXPIRY_TIME` where `0=never` otherwise parse the given duration.
- Determine what the behaviour is for the commercial Tailscale control plane and implement a similar flow. Are they using access/refresh tokens?

What would be the preferred approach to handling this @kradalby?

**Comment by jsiebens** [comment]
As OIDC tokens tend to be short-lived (with google it's 1h, with others perhaps even shorter), I wonder why machines should follow the same expiry.

On the commercial Tailscale server, newly registered machines get a fixed expiration period (default 180 days but can be configured on your tailnet using the admin console) unless they have ACL tags, then key expiry is disabled.
- https://tailscale.com/kb/1028/key-expiry/
- https://tailscale.com/kb/1068/acl-tags/#key-expiry-for-tagged-devices

**Comment by ported-pw** [comment]
> As OIDC tokens tend to be short-lived (with google it's 1h, with others perhaps even shorter), I wonder why machines should follow the same expiry.
Exactly. As I mentioned, for Keycloak the default is 5 minutes.

It would be okay if
1. Machines were expired once the OIDC session cannot be refreshed anymore (forces re-login at SSO provider)
and
2. Machines were expired if on token refresh the token does not match the required allowed groups/domains/etc. anymore

But if the original Tailscale behaviour is 180 days or a different configurable value on registration via OIDC, that would be fine too and I'd assume much easier to implement.

**Comment by Hacksawfred3232** [comment]
> The implementation uses whatever your OIDC provider puts in the exp-field of the issued token.
> 
> It may indicate that your provider has a default token lifetime of 1hr.
Following @evenh comment, trying to increase the token expiry time in Keycloak - which is what I use for my OIDC provider - it seems to only max out at 10 hours when Headscale updates a client. Which seems really random, so either a bug with Keycloak/OIDC implementation or built-in limitation. Though while the token time is fair in terms of short-lived tokens, some users may need it at max a month without making the OIDC provider insecure. Implementing  `HS_OVERRIDE_DEFAULT_EXPIRY_TIME` sounds like a good idea.

**Comment by ported-pw** [comment]
> Implementing HS_OVERRIDE_DEFAULT_EXPIRY_TIME sounds like a good idea.
I agree that it's an easy and acceptable stopgap solution.

**Comment by Hacksawfred3232** [comment]
> I won't have time to tackle the integration tests anytime soon, but could something like this work?
@evenh That patch seems to work! I'll roll with the patched version until it becomes added officially.

**Comment by kradalby** [comment]
I have created https://github.com/juanfont/headscale/pull/1191 based on @evenh's patch, it takes a slightly different approach:

Instead of adding an option to override the new behaviour (using the token expiry) it makes that an optional behaviour for people who desire it. 

Instead of reverting back to setting no expiry for OpenID clients, it will now align with Tailscale SaaS and set 180 days by default, and of course exposing the option to the user so it can be set longer or short as desired.

Please help testing it or voice concerns on the PR.
