### ISSUE TITLE
Unable to run in linux background using headscale.service

### ISSUE THREAD

**Issue by MDQ0512** [juanfont/headscale#1214]
Everything is normal. However, after configuring the headscale.service file, headscale cannot be started normally. The following error message is displayed

headscale.service - headscale controller
   Loaded: loaded (/etc/systemd/system/headscale.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2023-02-09 23:05:19 CST; 2s ago
  Process: 29425 ExecStart=/usr/local/bin/headscale serve (code=exited, status=1/FAILURE)
 Main PID: 29425 (code=exited, status=1/FAILURE)
Feb 09 23:05:19 VM-12-7-centos systemd[1]: headscale.service: main process exited, code=exited, status=1/FAILURE
Feb 09 23:05:19 VM-12-7-centos systemd[1]: Unit headscale.service entered failed state.
Feb 09 23:05:19 VM-12-7-centos systemd[1]: headscale.service failed.

**Comment by darientops** [comment]
Same here :(

**Comment by wsbadmf** [comment]
Hello.  I am having the same issue as well.  I tried setting the service as both headscale / headscale as well as root / root with the same result:

Feb 11 21:26:31 headscale systemd[1]: headscale.service: Scheduled restart job, restart counter is at 386.
Feb 11 21:26:31 headscale systemd[1]: Stopped headscale controller.
Feb 11 21:26:31 headscale systemd[1]: Started headscale controller.
Feb 11 21:26:31 headscale headscale[11585]: 2023-02-11T21:26:31Z INF ../../../home/runner/work/headscale/headscale/derp_server.go:92 > DERP>
Feb 11 21:26:31 headscale headscale[11585]: 2023-02-11T21:26:31Z INF STUN server started at [::]:3478
Feb 11 21:26:31 headscale headscale[11585]: 2023-02-11T21:26:31Z INF Setting up a DERPMap update worker frequency=86400000
Feb 11 21:26:31 headscale headscale[11585]: 2023-02-11T21:26:31Z FTL ../../../home/runner/work/headscale/headscale/cmd/headscale/cli/server>
Feb 11 21:26:31 headscale systemd[1]: headscale.service: Main process exited, code=exited, status=1/FAILURE
Feb 11 21:26:31 headscale systemd[1]: headscale.service: Failed with result 'exit-code'.

Worth mentioning there are two things in the instructions that confused me so I possibly got them wrong:

"Note that when running as the headscale user ensure that, either you add your current user to the headscale group:"
Seems like an incomplete statement.  For testing, I added root to the headscale group.  

And if you follow the instructions to create the headscale user with --shell /usr/bin/nologin   (I corrected to /usr/sbin/nologin) you can't su headscale due to the nologin shell.  "This account is currently not available"

Thank you for any advise.

**Comment by coding2dawn** [comment]
This issue can be done by running the command `sudo headscale serve` to generate the private key.

I guess you were using a sudo user to run headscale in the background with systemd.

**Comment by coding2dawn** [comment]
@MDQ0512 @darientops 
You can also replace the private key, the noise private key, and the db_path with  _/var/lib/headscale/_ instead of _./filename_
It worked for me.

**Comment by kradalby** [comment]
This is not an issue, but a support question, please continue the conversation on Discord.

**Comment by dev286** [comment]
I get this issue in Ubuntu 24.04 / Headscale 0.23.0 (also in 22.3 alpha 3/5/9).

_sudo headscale serve_ returns this:
WRN Failed to read configuration from disk error="While parsing config: yaml: line 12: did not find expected key"
2024-10-23T07:23:11Z FTL ../runner/work/headscale/headscale/cmd/headscale/cli/root.go:48 > Error loading config error="fatal error reading config file: While parsing config: yaml: line 12: did not find expected key"

I do have this in config file:  /var/lib/headscale/

I followed the official install docs.
