### ISSUE TITLE
IP address mask /32 causes issues with dnsmasq

### ISSUE THREAD

**Issue by eSoares** [juanfont/headscale#1216]
**Bug description**

I currently run headscale with minor changes from default configuration.
The address space used is `100.64.0.0/10`, but each client ends up with an IP address with mask `/32` by default.
This mask causes issues with `dnsmasq`, where it will ignore the interface and not answer correctly `dynamic-host` queries, since it indicates that address range is a single device instead of a network range of devices.
This issue was pointed [where](https://github.com/pi-hole/FTL/issues/1531#issuecomment-1430342537).

Such behavior makes running a DNS server harder and impossible to use a great feature when the server is exposed to multiple networks.

Is there a good reason for that network mask or a way to easily configure the network mask?

**Context info**

- Version of headscale used: the one currently in docker `latest` tag (0.20.0)
- Version of tailscale client: 1.34.1
- OS: Linux Raspbian bullseye
- Kernel version: 5.15.84-v7l+

**Comment by kradalby** [comment]
I do not think this is something we can do anything about, I believe the Tailscale client will (on most OS/platforms) try to assign the smallest route possible, and I do not think we can do anything about it. I cant seem to find the docs for this tho.

I will close this, but if you find information that we can otherwise do something about it, then feel free to reopen.
