### ISSUE TITLE
I hope that the next version can integrate self-checking derp, and can be accessed through ip, and is compatible with http/https protocol

### ISSUE THREAD

**Issue by shuncon** [juanfont/headscale#1242]
It is hoped that the next version can integrate self-checking derp, and can be accessed and used through ip or domain name without forcing the use of domain name, which is compatible with http/https protocol

**Comment by linsomniac** [comment]
Is this something the tailscale DERP server supports?  I haven't seen that the documentation says IP is supported, but I'm going by memory here, I seem to recall that documentation said you have to set up a domain.  If neither of those is true, you probably want to relabel this as a feature request rather than a bug report.

**Comment by juanfont** [comment]
Unfortunately the tailscale client requires DERP servers to have domain name and https.
