### ISSUE TITLE
ACL forbidden subnet routes should not be routed

### ISSUE THREAD

**Issue by ItsShadowCone** [juanfont/headscale#1331]
**Bug description**

Subnet routes which are inaccessible via ACL are still pushed to clients. A client who cannot access a specific subnet should not see it.

**To Reproduce**

- machine a advertising subnet routes
- machine b accepting routes
- ACL in place so b cannot access the subnet (i.e. via hosts). i.e. ACL present but missing for this subnet case.

**Context info**

Headscale 0.21.0, tailscale linux & android (latest as of writing).

**Comment by almereyda** [comment]
Still an issue AFAIK.

**Comment by ItsShadowCone** [comment]
I don't think this should be auto closed, we should take a look  still applies in the current version / alpha.

**Comment by almereyda** [comment]
There is ongoing work with #1604, which has just been pre-released in v0.23.0-alpha1.

**Comment by Murgeye** [comment]
I don't think this is the same Issue as #1604 and it is still an present in 0.23.0.

If you set a subnet route on node A and do not allow node B access to it in the ACLs, the route still gets pushed to node B. Node B will try routing all subnet traffic through it (and fail due to the ACL) - blocking all traffic to that subnet from node B even if node B is able to access that subnet from its own network.

**Comment by eopo** [comment]
I think this is still important, as it makes complicated network setups quite hard!
