### ISSUE TITLE
API for adding Extra Domain Records

### ISSUE THREAD

**Issue by athul** [juanfont/headscale#1356]
**Feature request**

Thank you for Headscale. I was trying it out to host a few servers under a single network so that inter server communication don't go unsecure. Some of the servers have their own domain name and magic dns routing always ends up with a SSL error when trying to use `curl`. I tried adding the same server as an A record in the config and it works perfectly.
  
The thing is we automate all these stuff and we could use Ansible to write to the config file once a server is added to the tailnet with the domain name and IP but would be great if this was doable via API. We already use the API to fetch details about the machines and the IPs and all those stuff.

Maybe it could be something like 
POST: `/api/v1/domains/extra`
Payload
```json
{
        "domain":"abc.xyz.example.com",
        "ip":"100.0.0.4"
}
```

**Comment by loprima-l** [comment]
Hi, thanks for your FR, won't it be better to try to fix your ssl issue ? And also, if you're using Headscale only between the server, it's not mandatory to use ssl as the communication is already encrypted between your servers.

Can you open an issue to describe your ssl problem a bit more ?

**Comment by loprima-l** [comment]
Oh i got it

**Comment by loprima-l** [comment]
And why don't you redirect all your traffic to abc.example.com ?

**Comment by 6ixfalls** [comment]
Even with the SSL issue resolved, this would still be a great feature to add. It would allow, for example, https://github.com/iFargle/headscale-webui to have a DNS records page, which would make it easy to update the configuration (without having to ssh into the control plane, and changing the configuration file). Of course, it would need to also have listing APIs as well as delete, and since they're already defined in the configuration file they'd have to be migrated or something.

**Comment by 6ixfalls** [comment]
If not (maybe design decisions), it would also be great to separate the DNS configuration from the main configuration, and automatically reload any new DNS configurations, so a control plane restart isn't required to change DNS records.

**Comment by loprima-l** [comment]
That's a good point I think the DNS API is as important than the ACL API, I will maybe do a PR for this when I got the time, I need to get a little bit more familiar with the code to start it and feel secure and confident.

**Comment by juanfont** [comment]
This is not a bad idea. We will probably look into it.

**Comment by stuartm** [comment]
Is anyone still working on this? Allowing DNS records to be managed via API? This really is a must-have for me so if no-one has made any progress on it I might have to take a look.

Friction point for me, aside from lack of spare time, is zero experience with Go but needs must.

If I were to take this on, would it be better for extra records to be persisted in the database instead of the extra_records json file? I'd be wary of corruption if using the json file directly without any locking (concurrent manual edits).

**Comment by stuartm** [comment]
So, Is that an official flat NO to allowing records to be managed through the API?

If it's not too bold a question, why? What's different about this than managing everything else through the API?

**Comment by kradalby** [comment]
@stuartm probably not going to add it to the API, it comes down to where the data is stored, extra records is not in the database, they are a file, and the API doesnt cover that.
