### ISSUE TITLE
Stop using gorilla mux

### ISSUE THREAD

**Issue by kev-the-dev** [juanfont/headscale#1478]
[Gorilla mux is a dead project, no long maintained](https://github.com/gorilla#gorilla-toolkit). It won't receive bug fixes or security patches.

[gin](https://github.com/gin-gonic/gin) seems to be a good alternative that has the most adoption for this purpose

**Comment by kradalby** [comment]
Hi!

We moved away from Gin as it made significantly more problems for us than it helped, we switched to Gorilla mux intentionally because it is stable and battle proven, we are not particularly concerned as we only use the router.

We might change it in the future, but we do not have a plan to action this now.
