### ISSUE TITLE
Bug in user switching during OIDC authentication

### ISSUE THREAD

**Issue by vsychov** [juanfont/headscale#1522]
## Bug description
Hello,

I found an issue in headscale that seems like a bug to me. 
As a user, I can't change the OIDC account I'm already authorized with. I'm trying to do it this way:
1. login as user1
2. logout, by: `tailscale logout && tailscale down`
3. login as user2: `tailscale up` with the `--login-server` parameter. It redirects me to the OIDC authorization page (`https://my-server.com/oidc/register/nodekey:XXXXXXX`)

Upon successful authorization, I get an error in the web interface:
`could not register machine`, and in the app logs, there's also an error: `ERR go/src/headscale/hscontrol/oidc.go:712 > could not register machine error="machine was previously registered with a different user"`

The error seems to be here, where it's explicitly forbidden:
https://github.com/juanfont/headscale/blob/fb203a2e454a9907d017ed3c61c7002ed3065977/hscontrol/db/machine.go#L381-L386

**Comment by vsychov** [comment]
Same issue is #1310, bug was caused by changes from https://github.com/juanfont/headscale/pull/754

**Comment by NetworkEngineer509** [comment]
Can confirm I am coming across this as well. I was just about to submit a bug report but came across this.

**Comment by micudaj** [comment]
same for me. just had this as well

**Comment by kolaente** [comment]
Any update on this?

**Comment by hannescl** [comment]
This bug "hit" me as well yesterday...

**Comment by mannp** [comment]
I have just got this error after setting up my first user with oidc.

`headscale-start[167399]: 2024-01-22T16:08:55Z ERR github.com/juanfont/headscale/hscontrol/oidc.go:712 > could not register machine error="machine was previously registered with a different user"`

**Comment by benmehlman** [comment]
I'm having a similar problem:

Headscale is installed and working (headscale v0.23.0-alpha5, on debian 12.4).

OIDC is set up using Google Workspace as the provider.
Connect tailscale client for linux, using my headscale server as the login-server.  Copy/paste oidc url, authenticate as a google workspace user.  Let's say "firstuser@mydomain.com".  It authenticates successfully.

Install tailscale client for windows (1.6.2).  Set registry values to point to my headscale server.  Select Login from the tailscale client menu.. it does OIDC auth in the browser.. authenticate using SAME google user as before, it works.

Everything works as configured (nodes can see each other, subnet route works, and configured dns server is used).  

(Amazing.. loving this.. thanks!).

Headscale shows two nodes up and one user, as expected.

Now I want to log out as my regular user and try logging in as a different user.. this is where the problem comes...
In the windows client, select my user.. then "Log out".  It appears to log out and disconnect.

Tailscale prompts me to log in.. I click and the oidc page comes up.  I select a DIFFERENT account in my workspace domain.  I get the validation page from my headscale server "Reauthenticated as seconduser@mydomain.com, you can now close this window".

Open the tailscale for Windows menu.. it shows that I'm connected NOT as "seconduser"  but as "firstuser".. and this is indicated by the headscale admin as well.  I'm connected again, but not as the user that I selected (and that appeared on the "Signed in via your OIDC provider" page....

LMK of any solution.. Thanks!

**Comment by W1BTR** [comment]
Any updates on this? Just came across this too, need **some** way to switch between multiple users.

**Comment by almereyda** [comment]
One workaround I heard about was running multiple `tailscaled` daemons and scoping the client to either of them. In addition to `tailscale0`, you would be able to also setup `tailscale1`, `tailscale2`, `tailscale…`, `tailscalen`. Unfortunately I have not tested it myself.
