### ISSUE TITLE
Dosn't work with `webvm.io`

### ISSUE THREAD

**Issue by calvinweb** [juanfont/headscale#1650]
## Bug description
dosnt work with webvm (which is built with tailscale's offical wasm library)

## Environment

- OS: Web platform
- Headscale version: v0.22.3
- Tailscale version: ...

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

```
headscale preauthkey create -u xxx
```
open `webvm.io/#controlUrl=xxx&authKey=yyy` in browser and the network link dosnt setup (If using tailscale's offical server, a ip will be shown)

**Comment by yuri91** [comment]
Webvm developer here, offering some context:

We managed to make headscale work with the wasm client in this fork: https://github.com/leaningtech/headscale

We always meant to try to upstream the changes, but it's not so simple.

In particular the main issue is that the ts2021 endpoint does not seem to work with a real websocket connection. We tried to fix it properly but with no avail.

See this commit message for more details: https://github.com/juanfont/headscale/commit/038126c8b88e34b5fb1aedc25e1bb42cc0e5041a

So our fork currently just disables the ts2021 endpoint, since if it's there, it will be tried first by the client.

There are a few more minor issues that we found and fixed in the other commit in our fork: https://github.com/juanfont/headscale/compare/main...leaningtech:headscale:main

These seem to be general issues/discrepancies compared to the official tailscale control plane that affect the time it takes to establish a proper connection.

If there is interest in upstreaming some of these changes let me know. I can also test any potential fix to the ts2021 endpoint in webvm.io if needed.

**Comment by calvinweb** [comment]
> These seem to be general issues/discrepancies compared to the official tailscale control plane that affect the time it takes to establish a proper connection.

Is opening a PR considered?

**Comment by kradalby** [comment]
The next version of Headscale will drop support for the old non-"noise" (ts2021) protocol, so if that isnt supported, it will likely not be possible to fix.

**Comment by yuri91** [comment]
It is supported when using the official Tailscale control plane.

A web client requests a regular websocket connection instead of upgrading the http connection to "tailscale-control-protocol". You can see the client changes they made here: https://github.com/tailscale/tailscale/commit/a9f32656f53e4dbe7248852a616af75072f89000

I tried back then to make Headscale work with this, but as the commit that disables ts2021 says: 

> We tried to add support by enabling GET requests to the ts2021 endpoint,
> but the connection is killed by some context cancelling before any data
> is exchanged (except for the noise handshake).
> Replacing a few contexts with context.Background() make it work after a
> few tries, but never clean on the first try.

I haven't tried since ~ a year ago, so maybe things changed

**Comment by calvinweb** [comment]
> [webvm.io](https://webvm.io) developer here, offering some context:
> 
> We managed to make headscale work with the wasm client in this fork: https://github.com/leaningtech/headscale
> 
> We always meant to try to upstream the changes, but it's not so simple.
> 
> In particular the main issue is that the ts2021 endpoint does not seem to work with a real websocket connection. We tried to fix it properly but with no avail.
> 
> See this commit message for more details: [038126c](https://github.com/juanfont/headscale/commit/038126c8b88e34b5fb1aedc25e1bb42cc0e5041a)
> 
> So our fork currently just disables the ts2021 endpoint, since if it's there, it will be tried first by the client.
> 
> There are a few more minor issues that we found and fixed in the other commits in our fork: [main...leaningtech:headscale:main](https://github.com/juanfont/headscale/compare/main...leaningtech:headscale:main)
> 
> These seem to be general issues/discrepancies compared to the official tailscale control plane that affect the time it takes to establish a proper connection.
> 
> If there is interest in upstreaming some of these changes let me know. I can also test any potential fix to the ts2021 endpoint in webvm.io if needed.

well, this fork can just let webvm connect to headscale and get a ip, but nothing is accessable inside webvm even it self

**Comment by yuri91** [comment]
@calvinweb please report this issue (with more details) in your existing issue open issue in the webvm repo: https://github.com/leaningtech/webvm/issues/93

The headscale fork does work, we have users actively using it. So maybe there is a configuration error.

I would keep this issue focused on the topic of supporting web clients in upstream Headscale.
