### ISSUE TITLE
Linux != Only Ubuntu & Debian

### ISSUE THREAD

**Issue by acidvegas** [juanfont/headscale#1795]
## Why

I am tired of seeing every major project on Github simply catered around people on Debian & Ubuntu. Not all of us have systemd or use simple distros like this.

## Description

I would be nice to see a setup/install guide that is more universal, rather than saying headscale "depends" upon Ubuntu & Debian. No offense but not everyone on Linux is using those 2 distros only lol....Like seriously, your "manual" install is considered "legacy" and "outdated" ?  Not everyone is a simpleton looking for a 1 click install dude....Linux is for POWER USERS lol....yall cater your shit for the baby distros that everyone starts off with?

**Comment by hrtkpf** [comment]
Since Headscale is also released as container images, you should be able to run it on any Linux distro supporting an OCI-compatible container runtime (Docker, Podman etc.). Alternatively, you could even compile the Go binary yourself.

If there is something wrong or missing in the docs, people are always welcome to open PRs!

**Comment by juanfont** [comment]
@acidvegas if you want to improve the docs, open a PR. 

In any case, I don't think this is in any way an appropriate manner to address the volunteer team of a community project.
