### ISSUE TITLE
Question: On the reason for not encouraging container and reverse proxy usage

### ISSUE THREAD

**Issue by LumenYoung** [juanfont/headscale#1818]
Could someone explain why the deployment of headscale with container and reverse proxy is not encouraged? Any difficulty or negative implication from that practice?

Sorry to use the bug report tag since I couldn't find appropriate tag for this issue. I searched through the issues but there is no answer to this. I believe this question is very common for  people read REDEME, by making it a public issue for people to search is going to save many explanation and confusions. Thanks for this great project BTW!

**Comment by juanfont** [comment]
Because it adds an extra layer of complexity and more failure modes to the system. 

For instance, many default configurations of reverse proxies do not handle WebSockets - which is an absolute requirement for Headscale. Or in the case of containers, you really have to have several mount points to get Headscale working.

Less tech saavvy users then have the impression that Headscale is broken, rather than their's setup. Which is why we ended having dedicated channels in Discord to support reverse proxies and docker.

For users familiar with containers and reverse proxies, there is nothing particularly difficult on getting Headscale working :)

**Comment by HWiese1980** [comment]
I got to say, I find the wording a bit... blunt. I understand that you do not _support_ it officially. Not _encouraging_ it however may lead to some people maybe not even _trying_, which might keep them from figuring stuff out others haven't yet. Maybe even bugs. After all, except for production use, stuff like this is practically _made_ to tinker with. I would recommend removing at least the "not encouraging" point, or at least emphasize not encouraging it particularly **in production**.

My two cents.
