### ISSUE TITLE
preauthkeys: Allow specifying key material

### ISSUE THREAD

**Issue by lorenzleutgeb** [juanfont/headscale#1855]
## Why

I deploy multiple machines (both machines that run the Tailscale client, but also a machine that runs the Headscale control server). I want to automate the registration of clients to the control server as much as possible.

At the moment, I have to run `headscale preauthkeys create` which will [randomly generate a 24 byte key](https://github.com/juanfont/headscale/blob/8a8e25a8d1e6bc5fa27b7f72f99bbf24b290e0a6/hscontrol/db/preauth_keys.go#L218-L226) and store it (along with additional metadata, such as expiry, user, etc.) in the SQLite database.

This means that in order to deploy a client, I first need to run a command on the control server to change its state, take the output, and use that to include it in the state to deploy to the client. Thus, I end up maintaining a list of preauth keys for my clients.

I would prefer to use the same list to also declaratively control the state of the control server. That is, I would like to set the list of preauth keys for the server (or at least add to the list), at the time I deploy it. This way I would be able to generate images for all clients and the control server, and deploy them "in one go", without having to first deploy the control server, executing `headscale preauthkyes create` and only then deploying clients.

## Description

I would like to be able to specify keys that I have securely generate myself when I execute `headscale preauthkeys create`, for example:

    headscale preauthkeys create --key da39a3ee5e6b4b0d3255bfef95601890afd80709ad001730 [...]

A workaround is to use the SQLite database directly, bypassing `headscale preauthkeys`, but I'd like to avoid that.

The implementation would be rather straightforward, adding another optional argument to pass the key, and if it is not specified call `generateKey` as it is done unconditionally at the moment.

**Comment by ohdearaugustin** [comment]
You can refer to this old discussion about such keys: https://github.com/juanfont/headscale/issues/662

**Comment by LEI** [comment]
I am using SSH to extract the output of `headscale apikey create` allowing automated pre-auth keys management via [API](https://github.com/awlsring/terraform-provider-headscale).

This is the only step that still requires direct SSH access, I see two ways to avoid it:
- define a static "bootstrap" API key in the configuration file,
- or add an option to specify the value when creating an API key.

In both cases I guess validation would ensure a long enough key is provided.
Let me know if it needs a dedicated issue.

**Comment by patsevanton** [comment]
This is still the missing piece for declarative VM bootstrap.

I provision Headscale with Terraform + cloud-init. I need the laptop and subnet-router preauth keys **before** the VM finishes booting, so they can live in `terraform.tfvars` and be passed into cloud-init (`tailscale up --authkey=...`) in the same apply. Today that is impossible: `headscale preauthkeys create` always generates the key on the server, so Terraform has to SSH back in, wait for cloud-init, and scrape `/var/lib/headscale/laptop-preauth.key`. That race is fragile (install starts the unit on the default config, health check on :443 fails, key file is never written).

What I want is exactly the flag from this issue:

```
headscale preauthkeys create --user <id> --reusable --expiration 24h --key <hex>
```

If `--key` is omitted, keep generating a random key as today. If it is set, store that value (with the usual length/format checks) instead of calling `generateKey`.

Then the flow is: generate two keys locally → put them in tfvars → cloud-init writes config, starts Headscale, creates the user, registers those preauth keys, and `tailscale up` uses the same strings. No SSH fetch, no chicken-and-egg with the API key.

I would rather not INSERT into SQLite by hand. Is `--key` still off the table, or would you take a small PR for it?

**Comment by kradalby** [comment]
Please do not post on old closed threads, as so much has changed since they were closed.

The next release will support parts of the tailscale terraform provider, including auth keys and it should likely solve your issue.
