### ISSUE TITLE
[Feature] Restricted nameservers without search domains

### ISSUE THREAD

**Issue by casdr** [juanfont/headscale#1936]
### Use case

I use the `restricted_nameservers` option for my own implementation of App Connectors (the DNS server adds routes to the subnet router) so I can route services like 1Password over the tailnet. The issue with the current implementation is that 1password.com will also be added as a search domain, which I don't want.

### Description

It would be nice if it was possible to add a restricted nameserver without the domain being added as a searchdomain.

### Contribution

- [ ] I can write the design doc for this feature
- [ ] I can contribute this feature

### How can it be implemented?

I've been digging in the Tailscale client sourcecode, and I think this can be implemented by adding the domain to `DNSConfig.MatchDomains` instead of `DNSConfig.SearchDomains`, but I'm not really sure about this.

**Comment by casdr** [comment]
I will dig into this a little bit further tomorrow and see if I can implement this myself.

**Comment by Hypnotist1148** [comment]
I am facing the same issue, it's really frustrating especially because I get some dns resolution errors because of this.

**Comment by code-sigil** [comment]
My current fix is a slight modification of the v0.22.3 code, where I remove line 448 from the file hscontrol/config.go . This keeps headscale from appending the restricted servers to the search domains.

**Comment by SuperSandro2000** [comment]
I think DNSConfig.MatchDomains is filled via https://github.com/tailscale/tailscale/blob/218110963dbb12002529a4a91ffc149b70ac21ac/net/dns/manager.go#L325 and https://github.com/tailscale/tailscale/blob/7aec8d4e6b4e72d5053d9ff7d819c28f9e035c2c/net/dns/config.go#L146

Especially because of https://github.com/tailscale/tailscale/blob/7aec8d4e6b4e72d5053d9ff7d819c28f9e035c2c/net/dns/config.go#L148 I think we only need to fill Routes and not Domains. https://github.com/tailscale/tailscale/blob/7aec8d4e6b4e72d5053d9ff7d819c28f9e035c2c/tailcfg/tailcfg.go#L1568

**Comment by kradalby** [comment]
I think we have implemented this wrongly the whole time, looking into it now, it does not seem that tailscale saas, nor the client adds split dns to search domains, and I dont think there is a good reason to do it. I will address this as part of #2034.
