### ISSUE TITLE
can't check the mac device's name 

### ISSUE THREAD

**Issue by pppaapp** [juanfont/headscale#216]
<img width="399" alt="1" src="https://user-images.githubusercontent.com/31263588/140732206-0325fba8-5c07-48c2-b744-2cfea3bb37a5.png">

![2](https://user-images.githubusercontent.com/31263588/140732263-66e457da-5d3b-4fdc-a7e3-ead1565aad8b.png)

Linux devices don't have any problems

<img width="297" alt="3" src="https://user-images.githubusercontent.com/31263588/140732628-aab87ce2-4b3f-444b-bc61-0f61777db4e3.png">

but there's a problem with MAC devices

**Comment by 0xcd0e** [comment]
The problem here is not the OS, but the name of the machine.
Ive just tried this with two VMs, and when I joined one of them with --hostname TestVM1 I get the same behavior (MagicDNS not working), the other VM is unable to resolve the name, even if I manually type it out, using the correct casing.
But when I join it with --hostname testvm1 everything works as expected.

**Comment by 0xcd0e** [comment]
It looks like this is a problem in the tailscale client because the client expects the server to handle names differently.
When I join a new device to the official tailscale server and use --hostname TS-Test1 the server will set the machine name to ts-test1 and the OS Hostname to TS-Test1.
When I join a new device to headscale and use --hostname TS-Test1 the server will set the machine name to TS-Test1 and the OS Hostname to TS-Test1.

**Comment by pppaapp** [comment]
the problem seems to be resolved😀
