### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by kradalby** [juanfont/headscale#222]
Explore the use of our gRPC client to create a terraform provider.

The code can be generated from proto (or imported from the gen directory) and how it can be used can be found in the cli client.

**Comment by fdelucchijr** [comment]
this would be an awesome feature!!!

**Comment by engineeringsys** [comment]
There's work being done [here](https://github.com/davidsbond/terraform-provider-tailscale) for Tailscale.   One could start [here](https://github.com/davidsbond/terraform-provider-tailscale/blob/044ee6a7ee6e0b616d17e6682f02f44d7b177b07/internal/tailscale/client.go#L35)

**Comment by samcday** [comment]
Now that there's an official Tailscale provider plugin publish [in the registry](https://registry.terraform.io/providers/tailscale/tailscale/latest/docs), that seems to support pointing at a [custom base URL](https://registry.terraform.io/providers/tailscale/tailscale/latest/docs#base_url), would it perhaps make more sense to try to emulate whatever API calls the provider needs from the official Tailscale control plane?

In that case, the toil of building and maintaining a headscale Terraform provider can be completely avoided. Instead, some documentation would need to be maintained indicating which resources are supported from the official provider, what caveats there are, etc.

In the case of resources that headscale doesn't yet support (which I assume would be a lot of it, at least for now, since ACLs are derived from static filesystem metadata currently and so on), the emulated API layer could simply barf errors to signal this unsupported usage.

I'm not sure if there's been discussion in the past about doing something like this (emulating the official/proprietary control plane API), though I wouldn't be surprised if there has and it's fraught with lots of complexities I haven't even begun to consider :D

**Comment by unusualevent** [comment]
I really like the idea of having headscale support the tailscale terraform provider - is there a way to test the coverage between the two interfaces in some kind of unit test?

**Comment by kradalby** [comment]
It is unfeasible, the APIs are not the same.

**Comment by awlsring** [comment]
I wrote a manual provider utilizing the API gen'ed from the swagger doc.

https://registry.terraform.io/providers/awlsring/headscale/latest

If y'all like this, let me know and I can make a PR adding some usage to the docs.

**Comment by kradalby** [comment]
@awlsring, neat, it could also be listed in the readme in the same way as we list UIs atm.

**Comment by awlsring** [comment]
@kradalby Sure thing.

Looking at the readme, I was thinking of just renaming the section `Graphical Control Panels` to `Control Planes` and listing as a box in there.

I'll try to send out a PR for it in a few days

**Comment by kradalby** [comment]
I will close this as out of scope, we happy with a community provider
