### ISSUE TITLE
Support Split DNS

### ISSUE THREAD

**Issue by coelho** [juanfont/headscale#822]
**Feature request**

Split DNS is unsupported currently by Headscale. However, it can easily be supported!

It looks like `dnsConfig.Resolvers` decides whether or not the client overrides its Local DNS resolvers. If you comment out this line, Split DNS works perfectly:
https://github.com/juanfont/headscale/blob/main/config.go#L400

Would like feedback on how you would prefer this is implemented:
- `dns_config.override_dns (default: true)` configuration flag (sets "Resolvers" if "true")
- `dns_config.split_dns (default: false)` configuration flag (unsets "Resolvers" if "true")
- `dns_config.resolvers (default: alias to dns_config.nameservers)` configuration flag. 
  - Users can apply `dns_config.resolvers: []` to enable Split DNS.

Can submit a PR if you'd like based on feedback :) Thanks!

**Comment by kradalby** [comment]
Happy to take a PR with the work and some tests :)

**Comment by madjam002** [comment]
> 

Perhaps just a new config option `dns_config.fallback_nameservers` where the nameservers can be set but they're only used as a fallback, thus enabling Split DNS. `dns_config.nameservers` could then be left unset to enable Split DNS.

I've got split DNS working in my environment by renaming `dnsConfig.Resolvers` to `dnsConfig.FallbackResolvers` rather than commenting it out altogether.

**Comment by coelho** [comment]
@madjam002 Yes, but the operator should still have the option to not override at all if Split DNS is incompatible. That would be my preference.

**Comment by kradalby** [comment]
I will close this as it might have been fixed in newer version, please try a new release and reopen if it still does not work.
