### ISSUE TITLE
Version output in completion script

### ISSUE THREAD

**Issue by FredericIV** [juanfont/headscale#839]
**Bug description**
When generating autocompletion scripts, headscale outputs a version warning (below) into the completion script, causing an error in bash.

ESC[90m2022-09-27T17:56:46ZESC[0m ESC[31mWRNESC[0m Failed to read configuration from disk ESC[36merror=ESC[0mESC[31m"Config File \"config\" Not Found in \"[/etc/headscale /root/.headscale /root]\""ESC[0m
ESC[90m2022-09-27T17:56:46ZESC[0m ESC[31mWRNESC[0m 'ip_prefixes' not configured, falling back to default: [100.64.0.0/10]
An updated version of Headscale has been found (0.17.0-alpha4 vs. your current v0.16.4). Check it out https://github.com/juanfont/headscale/releases

**To Reproduce**
Execute the following as root.
`headscale completion bash > /etc/bash_completion.d/headscale`

**Context info**
Headscale: v0.16.4 (0.17.0-alpha4 is out at time of writing)
Platform: Fedora 36, Linux 5.19.11

**Comment by huskyii** [comment]
set `disable_check_updates: true` in the config should remove the version info.

**Comment by mhameed** [comment]
disable_check_updates: true is a work around, but not a proper fix.

I would argue that the update check should not be performed for "completion", as the output is expected to be parsed by another process, rather than a human, either that, or don't do the update check at all, but expose it via its own commandline argument.

Thanks.
